"""Tests for the auto-generated column marker and its use in TableSchema."""

import pytest

from warp.domain.schema import ColumnSchema, TableSchema


def col(name: str, **kwargs) -> ColumnSchema:
    kwargs.setdefault("type", "int")
    return ColumnSchema(name=name, **kwargs)


class TestIsAutoGenerated:
    @pytest.mark.parametrize(
        "column",
        [
            col("id", extra="auto_increment"),
            col("id", default="nextval('users_id_seq'::regclass)"),
            col("id", extra="identity"),
            col("total", extra="computed"),
            col("id", default="GENERATED ALWAYS AS IDENTITY"),
        ],
    )
    def test_generated(self, column):
        assert column.is_auto_generated is True

    @pytest.mark.parametrize(
        "column",
        [
            col("name"),
            col("n", default="0"),
            col("n", default=0),
            col("n", extra=""),
            col("flag", type="bit", default="1"),
        ],
    )
    def test_not_generated(self, column):
        assert column.is_auto_generated is False


class TestTableColumns:
    def test_required_and_insertable_skip_generated_columns(self):
        table = TableSchema(
            table_name="orders",
            primary_key="id",
            columns=[
                col("id", nullable=False, extra="identity"),
                col("total", type="money", nullable=False, extra="computed"),
                col("name", type="nvarchar", nullable=False),
                col("note", type="text", nullable=True),
                col("created", type="datetime2", nullable=False, default="sysutcdatetime()"),
                col("seq", nullable=False, default="nextval('s')"),
            ],
        )
        assert table.get_required_columns() == ["name"]
        assert table.get_insertable_columns() == ["name", "note", "created"]
